language: java
jdk: oraclejdk8
dist: trusty

# Make the gradle wrapper executable
# before_install: chmod +x gradlew
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.1.1-all.zip
  - unzip -qq gradle-6.1.1-all.zip
  - export GRADLE_HOME=$PWD/gradle-6.1.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle check jacocoTestReport
  # Also upload test coverage to codecov
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/